spring:
  datasource:
    url: jdbc:mysql://localhost/casa_do_codigo
    username: root
    password: 2002
    driverClassName: com.mysql.jdbc.Driver
#    testWhileIdle: true
#    validationQuery: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
